-- 코드를 입력하세요
SELECT AUTHOR_ID
    , AUTHOR_NAME
    , CATEGORY
    , SUM(SALES * PRICE) AS TOTAL_SALES 
FROM (
    SELECT BOOK_ID, SALES
    FROM BOOK_SALES 
    WHERE DATE_FORMAT(SALES_DATE, '%Y-%m-%d') LIKE '2022-01%'
    ) A
JOIN BOOK B
USING (BOOK_ID)
JOIN AUTHOR C
USING (AUTHOR_ID)

GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC
;