-- 코드를 입력하세요
-- 입양 간 동물 = ANIMAL_OUT에 입력된 동물 = INNER JOIN
-- 보호 기간 젤 길다 = (입양간 날짜 - 보호소 들어온 날짜) 젤 크다 
SELECT A.ANIMAL_ID
    , A.NAME
    # , TIMESTAMPDIFF(DAY, A.DATETIME, B.DATETIME) AS DIFF
FROM ANIMAL_INS A
JOIN ANIMAL_OUTS B USING (ANIMAL_ID)
ORDER BY TIMESTAMPDIFF(DAY, A.DATETIME, B.DATETIME) DESC
LIMIT 2
;