
# # -- 2022년 11월 1일 ~ 2022년 11월 30일 대여 가능하려면 = (START_DATE&)END_DATE가 11월 1일 이전
# # -- JOIN하면서 이전테이블의 CAR_ID가 이거인거랑 = ? JOIN하고 CAR_ID 동일한거 
# # -- 요금 적용 예시보면서 파악하기 : 일일 금액에 할인 적용한 금액에 * 30
# SELECT CAR_ID
#     , CAR_TYPE
#     , ROUND((DAILY_FEE * (1-DISCOUNT_RATE/100)) * 30 , 0) AS FEE
# FROM CAR_RENTAL_COMPANY_CAR A
# JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B USING (CAR_ID)
# JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C USING (CAR_TYPE)
# WHERE CAR_TYPE IN ('세단', 'SUV')
# AND (DATE_FORMAT(END_DATE, '%Y-%m-%d') < '2022-11-01'
#      OR DATE_FORMAT(START_DATE, '%Y-%m-%d') > '2022-11-30')
# AND DURATION_TYPE = '30일 이상'
# AND ROUND((DAILY_FEE * (1-DISCOUNT_RATE/100)) * 30 , 0) >= 500000 
# AND ROUND((DAILY_FEE * (1-DISCOUNT_RATE/100)) * 30 , 0) < 2000000
# GROUP BY CAR_ID
# ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC
# ;

# SELECT *
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
# WHERE CAR_ID IN (27, 18)

SELECT CAR_ID
    , CAR_TYPE
    , ROUND((DAILY_FEE * (1-DISCOUNT_RATE/100)) * 30 , 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR 
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C USING (CAR_TYPE)
WHERE CAR_ID NOT IN (
                    SELECT CAR_ID
                    FROM CAR_RENTAL_COMPANY_CAR A
                    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B USING(CAR_ID)
                    WHERE '2022-11' BETWEEN DATE_FORMAT(START_DATE, '%Y-%m') AND DATE_FORMAT(END_DATE, '%Y-%m')
                    )
AND CAR_TYPE IN ('세단', 'SUV')
AND DURATION_TYPE = '30일 이상'
AND ROUND((DAILY_FEE * (1-DISCOUNT_RATE/100)) * 30 , 0) >= 500000 
AND ROUND((DAILY_FEE * (1-DISCOUNT_RATE/100)) * 30 , 0) < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC