-- 2022년 11월 1일 ~ 2022년 11월 30일 대여 가능하려면 = 년 바뀔때는 범위 주의 
-- JOIN하면서 이전테이블의 CAR_ID가 이거인거랑 = ? JOIN하고 CAR_ID 동일한거 
-- 요금 적용 예시보면서 파악하기 : 일일 금액에 할인 적용한 금액에 * 30

# SELECT *
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
# WHERE CAR_ID IN (27, 18)

# SELECT CAR_ID
#     , CAR_TYPE
#     , ROUND((DAILY_FEE * (1-DISCOUNT_RATE/100)) * 30 , 0) AS FEE
# FROM CAR_RENTAL_COMPANY_CAR 
# JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C USING (CAR_TYPE)
# WHERE CAR_ID NOT IN (
#                     SELECT CAR_ID
#                     FROM CAR_RENTAL_COMPANY_CAR A
#                     JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B USING(CAR_ID)
#                     WHERE '2022-11' BETWEEN DATE_FORMAT(START_DATE, '%Y-%m') AND DATE_FORMAT(END_DATE, '%Y-%m')
#                     )
# AND CAR_TYPE IN ('세단', 'SUV')
# AND DURATION_TYPE = '30일 이상'
# AND ROUND((DAILY_FEE * (1-DISCOUNT_RATE/100)) * 30 , 0) >= 500000 
# AND ROUND((DAILY_FEE * (1-DISCOUNT_RATE/100)) * 30 , 0) < 2000000
# ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC
# ;

SELECT A.CAR_ID
    , A.CAR_TYPE
    , ROUND((A.DAILY_FEE * (1-C.DISCOUNT_RATE/100)) * 30 , 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR A
    , CAR_RENTAL_COMPANY_DISCOUNT_PLAN C 
WHERE A.CAR_TYPE = C.CAR_TYPE
AND A.CAR_ID NOT IN (
                    SELECT B.CAR_ID
                    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B
                    WHERE A.CAR_ID = B.CAR_ID
                    AND '2022-11' BETWEEN DATE_FORMAT(B.START_DATE, '%Y-%m') AND DATE_FORMAT(B.END_DATE, '%Y-%m')
                    )
AND A.CAR_TYPE IN ('세단', 'SUV')
AND C.DURATION_TYPE = '30일 이상'
AND ROUND((A.DAILY_FEE * (1-C.DISCOUNT_RATE/100)) * 30 , 0) >= 500000 
AND ROUND((A.DAILY_FEE * (1-C.DISCOUNT_RATE/100)) * 30 , 0) < 2000000
ORDER BY FEE DESC, A.CAR_TYPE, A.CAR_ID DESC
;