-- 코드를 입력하세요
SELECT YEAR(O.SALES_DATE) YEAR
    , MONTH(O.SALES_DATE) MONTH
    , U.GENDER 
    , COUNT(DISTINCT U.USER_ID) USERS
FROM USER_INFO  U
    , ONLINE_SALE O
WHERE U.USER_ID = O.USER_ID
GROUP BY YEAR
    , MONTH
    , GENDER
HAVING GENDER IS NOT NULL
ORDER BY YEAR
    , MONTH
    , GENDER
;