-- 코드를 입력하세요
SELECT A.PRODUCT_ID
    , B.PRODUCT_NAME
    , SUM(A.AMOUNT) * B.PRICE AS TOTAL_SALES
FROM FOOD_ORDER A
JOIN FOOD_PRODUCT B USING(PRODUCT_ID)
WHERE PRODUCE_DATE LIKE '2022-05%'
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID
;