SELECT HISTORY_ID
    , CASE WHEN DISCOUNT_RATE IS NOT NULL THEN ROUND(A.DAILY_FEE * (1-DISCOUNT_RATE/100) * DAY, 0)
           ELSE A.DAILY_FEE * DAY    
      END AS FEE
FROM (  SELECT *
            , TIMESTAMPDIFF(DAY, B.START_DATE, B.END_DATE) +1 AS DAY
            , CASE WHEN TIMESTAMPDIFF(DAY, B.START_DATE, B.END_DATE) +1 >= 90 THEN '90일 이상'
                   WHEN TIMESTAMPDIFF(DAY, B.START_DATE, B.END_DATE) +1 >= 30 THEN '30일 이상'
                   WHEN TIMESTAMPDIFF(DAY, B.START_DATE, B.END_DATE) +1 >= 7 THEN '7일 이상'
              END AS DURATION_TYPE
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B 
        JOIN CAR_RENTAL_COMPANY_CAR A USING (CAR_ID)
        WHERE A.CAR_TYPE = '트럭'
     ) A
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B USING (CAR_TYPE, DURATION_TYPE)
ORDER BY FEE DESC, HISTORY_ID DESC
;
