SELECT A.SCORE
    , A.EMP_NO
    , B.EMP_NAME
    , B.POSITION
    , B.EMAIL
FROM (  SELECT EMP_NO, SUM(SCORE) AS SCORE
        FROM HR_GRADE 
        WHERE YEAR = 2022
        GROUP BY EMP_NO
        ORDER BY SCORE DESC
        LIMIT 1
     ) AS A
JOIN HR_EMPLOYEES AS B 
USING (EMP_NO)
;