-- 코드를 입력하세요
SELECT CATEGORY
    , SUM(SALES) AS TOTAL_SALES
FROM (
        SELECT BOOK_ID, SALES
        FROM BOOK_SALES 
        WHERE DATE_FORMAT(SALES_DATE, '%Y-%m-%d') LIKE '2022-01%'
) A
JOIN BOOK B USING (BOOK_ID)
GROUP BY CATEGORY
ORDER BY CATEGORY
;